#!/bin/sh
# ================================================================
#  BuddyChat XP one-line installer for macOS and Linux.
#
#  Usage:
#    curl -fsSL https://aetex.is-a.dev/buddyxp/install.sh | sh
#
#  Or download and run locally:
#    sh install.sh
#
#  What it does:
#    1. Downloads the latest BuddyChat XP release tarball from GitHub.
#    2. Extracts it to a per-user data directory
#       ($XDG_DATA_HOME/buddyxp, or ~/.local/share/buddyxp).
#    3. Creates a `buddyxp` command in ~/.local/bin that wraps launch.sh.
#    4. Adds ~/.local/bin to PATH if it isn't already there.
#
#  Uninstall:
#    rm -rf "${XDG_DATA_HOME:-$HOME/.local/share}/buddyxp"
#    rm -f  "$HOME/.local/bin/buddyxp"
#    Then remove the "buddyxp-PATH" block from your shell rc file.
# ================================================================

set -e

VERSION="0.1.0"
REPO="Aetex/buddyxp"

OS_NAME="$(uname -s)"

INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/buddyxp"
BIN_DIR="$HOME/.local/bin"
SHIM_PATH="$BIN_DIR/buddyxp"

echo ""
echo "  ============================================================"
echo "    BuddyChat XP Installer"
echo "    AeteX Interactive  -  Est. 2025"
echo "  ============================================================"
echo ""
echo "    OS:                $OS_NAME"
echo "    Install location:  $INSTALL_DIR"
echo "    Version:           $VERSION"
echo ""

# ---------------------------------------------------------------
# Check for a static-server runtime
# ---------------------------------------------------------------

has_cmd() { command -v "$1" >/dev/null 2>&1; }

HAS_PY=0
if has_cmd python3 || has_cmd python; then HAS_PY=1; fi
HAS_NODE=0
if has_cmd node; then HAS_NODE=1; fi

if [ "$HAS_PY" = "0" ] && [ "$HAS_NODE" = "0" ]; then
    echo "  WARNING: Neither Python nor Node.js was found."
    echo "           BuddyChat XP needs one of them to serve files."
    echo ""
    echo "  Install one of these first, then re-run this installer:"
    case "$OS_NAME" in
        Darwin)
            echo "      brew install python3"
            echo "      # or"
            echo "      brew install node"
            ;;
        *)
            echo "      See your distro's package manager."
            echo "      Debian/Ubuntu:  sudo apt install python3"
            echo "      Fedora/RHEL:    sudo dnf install python3"
            echo "      Arch:           sudo pacman -S python"
            ;;
    esac
    echo ""
    printf "  Continue anyway? [y/N] "
    # Read from /dev/tty so this works even when piped from curl.
    if [ -r /dev/tty ]; then
        read -r answer </dev/tty || answer=""
    else
        answer=""
    fi
    case "$answer" in
        [Yy]*) ;;
        *) echo "  Install cancelled."; exit 0 ;;
    esac
    echo ""
fi

# ---------------------------------------------------------------
# Download and extract
# ---------------------------------------------------------------

TMP_DIR="$(mktemp -d 2>/dev/null || mktemp -d -t buddyxp)"
cleanup() {
    if [ -d "$TMP_DIR" ]; then rm -rf "$TMP_DIR"; fi
}
trap cleanup EXIT INT TERM

URL="https://github.com/$REPO/archive/refs/tags/v$VERSION.tar.gz"
ARCHIVE="$TMP_DIR/buddyxp.tar.gz"

echo "  Downloading..."
if ! curl -fsSL "$URL" -o "$ARCHIVE"; then
    echo "  Could not download from $URL" >&2
    exit 1
fi

echo "  Extracting..."
if ! tar -xzf "$ARCHIVE" -C "$TMP_DIR"; then
    echo "  Could not extract archive" >&2
    exit 1
fi

EXTRACTED="$TMP_DIR/buddyxp-$VERSION"
if [ ! -d "$EXTRACTED" ]; then
    EXTRACTED="$(find "$TMP_DIR" -maxdepth 1 -type d -name 'buddyxp-*' | head -n 1)"
fi
if [ ! -d "$EXTRACTED" ]; then
    echo "  Could not find the extracted folder" >&2
    exit 1
fi

# ---------------------------------------------------------------
# Install
# ---------------------------------------------------------------

echo "  Installing to $INSTALL_DIR..."
if [ -d "$INSTALL_DIR" ]; then
    rm -rf "$INSTALL_DIR"
fi
mkdir -p "$INSTALL_DIR"

# Copy contents including dotfiles. cp -R src/. dst/ is the portable way.
cp -R "$EXTRACTED"/. "$INSTALL_DIR"/

# Ensure launchers are executable
chmod +x "$INSTALL_DIR/launch.sh"        2>/dev/null || true
chmod +x "$INSTALL_DIR/launch-node.js"   2>/dev/null || true
chmod +x "$INSTALL_DIR/launch-python.py" 2>/dev/null || true

# ---------------------------------------------------------------
# Create the buddyxp shim
# ---------------------------------------------------------------

mkdir -p "$BIN_DIR"

cat > "$SHIM_PATH" <<SHIM
#!/bin/sh
# BuddyChat XP shim - auto-generated by install.sh
# Do not edit this file. Re-run the installer to regenerate.
exec "$INSTALL_DIR/launch.sh" "\$@"
SHIM

chmod +x "$SHIM_PATH"
echo "  Created $SHIM_PATH"

# ---------------------------------------------------------------
# Add $BIN_DIR to PATH
# ---------------------------------------------------------------

path_has_bindir() {
    case ":$PATH:" in
        *":$BIN_DIR:"*) return 0 ;;
        *)              return 1 ;;
    esac
}

if path_has_bindir; then
    echo "  $BIN_DIR already in PATH"
else
    # Pick the rc file that matches the user's login shell.
    case "${SHELL:-}" in
        */zsh)  RC_FILE="$HOME/.zshrc" ;;
        */bash) RC_FILE="$HOME/.bashrc" ;;
        */fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
        *)      RC_FILE="$HOME/.profile" ;;
    esac

    if [ ! -f "$RC_FILE" ]; then
        RC_FILE="$HOME/.profile"
    fi

    # Only append if we haven't already been here.
    if ! grep -qs "buddyxp-PATH" "$RC_FILE" 2>/dev/null; then
        {
            echo ""
            echo "# Added by BuddyChat XP installer (buddyxp-PATH)"
            echo 'export PATH="$HOME/.local/bin:$PATH"'
        } >> "$RC_FILE"
        echo "  Added $BIN_DIR to PATH in $RC_FILE"
    else
        echo "  PATH entry already present in $RC_FILE"
    fi
fi

# ---------------------------------------------------------------
# Done
# ---------------------------------------------------------------

echo ""
echo "  ============================================================"
echo "    Installation complete."
echo "  ============================================================"
echo ""
echo "  Next steps:"
echo "    1. Open a new terminal, or run:"
echo "         export PATH=\"\$HOME/.local/bin:\$PATH\""
echo "    2. Run:  buddyxp"
echo ""
echo "  To update later, re-run this installer."
echo ""
echo "  To uninstall:"
echo "    rm -rf \"$INSTALL_DIR\""
echo "    rm -f  \"$SHIM_PATH\""
echo "    Then remove the \"buddyxp-PATH\" block from your shell rc file."
echo ""